apiVersion: v1
kind: Pod
metadata:
  name: toolbox
spec:
  restartPolicy: Never
  containers:
  - name: toolbox
    image: ser1zw/toolbox:latest
    imagePullPolicy: Always
    command: ["/bin/sleep", "infinity"]
    resources:
      limits:
        memory: "2Gi"
      requests:
        memory: "1Gi"
    volumeMounts:
      - name: work-storage
        mountPath: /home/metal/data
  volumes:
    - name: work-storage
      emptyDir: {}
